# Generated by Django 5.0.6 on 2024-06-20 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=50)),
                ('id_proof', models.CharField(max_length=100)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TushionApp.classstudy')),
                ('Login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TushionApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('replay', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('Date', models.DateField(max_length=15)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TushionApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(max_length=20)),
                ('pstatus', models.CharField(max_length=50)),
                ('hour', models.CharField(max_length=50)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TushionApp.classstudy')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TushionApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectName', models.CharField(max_length=100)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TushionApp.classstudy')),
            ],
        ),
        migrations.CreateModel(
            name='TestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_name', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(max_length=20)),
                ('FromTime', models.TimeField(max_length=20)),
                ('ToTime', models.TimeField(max_length=20)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TushionApp.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.BigIntegerField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TushionApp.student')),
                ('TestDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TushionApp.testdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=20)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TushionApp.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('experience', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=50)),
                ('id_proof', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('Login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TushionApp.login')),
            ],
        ),
        migrations.AddField(
            model_name='testdetails',
            name='Tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TushionApp.tutor'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(max_length=50)),
                ('Time', models.TimeField(max_length=10)),
                ('message', models.CharField(max_length=100)),
                ('Tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TushionApp.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Mysubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TushionApp.subjects')),
                ('Tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TushionApp.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('Date', models.DateField(max_length=15)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TushionApp.student')),
                ('Tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TushionApp.tutor')),
            ],
        ),
    ]
