# Generated by Django 5.0.6 on 2024-07-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TushionApp', '0003_notification_mysubject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classstudy',
            old_name='className',
            new_name='ClassName',
        ),
    ]
